Repository youniversityupc/app, pull requests merged in 2022-11, with the labels that each got.

#13 chore: disable web target
  web/favicon.png
  web/icons/Icon-192.png
  web/icons/Icon-512.png
  web/icons/Icon-maskable-192.png
  web/icons/Icon-maskable-512.png
  web/index.html
  web/manifest.json
Labels: chore

#12 feat: default global app theme
  assets/mask.png
  lib/components/course_card.dart
  lib/components/cover_widget.dart
  lib/layout/app_layout.dart
  lib/layout/app_navigation.dart
  lib/layout/app_theme.dart
  lib/main.dart
  lib/pages/auth/auth_location.dart
  lib/pages/auth/sign_in_page.dart
  lib/pages/auth/sign_up_page.dart
  lib/pages/auth/signin_page.dart
  lib/pages/auth/signup_page.dart
  lib/pages/grades/grades_detail_page.dart
  lib/pages/grades/grades_information.dart
  lib/pages/grades/models/assignment_grade_model.dart
  lib/pages/home/home_courses_page.dart
  lib/pages/profile/profile_settings_page.dart
  lib/utils/app_colors.dart
  lib/utils/build_context_extensions.dart
  lib/utils/named_font_weight.dart
  lib/utils/text_style_extensions.dart
  lib/utils/widget_list_extensions.dart
  pubspec.lock
  pubspec.yaml
  test/routing_test.dart
Labels: enhancement

#10 feat: activity pages
  lib/layout/route_constants.dart
  lib/pages/activities/activities_location.dart
  lib/pages/activities/activity_form.dart
  lib/pages/activities/activity_page.dart
  lib/pages/activities/components/activity_card.dart
  lib/pages/activities/models/activity_model.dart
Labels: enhancement

#14 feat: course page
  lib/pages/courses/components/course_card.dart
  lib/pages/courses/course_page.dart
  lib/pages/courses/courses_location.dart
  lib/pages/courses/models/course_model.dart
Labels: enhancement

#15 ci: add PR dependency check
  .github/workflows/prcheck.yml
Labels: ci

#16 feat: home today page
  lib/pages/home/home_location.dart
  lib/pages/home/home_today_page.dart
Labels: enhancement

#8 feat: add delegate information
  assets/dalb.jpg
  lib/pages/courses/create_delegate_page.dart
  lib/pages/courses/delegate_info_page.dart
Labels: enhancement

#22 refactor: update card dependencies
  lib/components/course_card.dart
  lib/pages/activities/activity_page.dart
  lib/pages/activities/components/activity_card.dart
  lib/pages/courses/components/course_card.dart
  lib/pages/courses/course_page.dart
  lib/pages/home/home_courses_page.dart
  lib/pages/home/home_today_page.dart
Labels: refactor

#24 fix: deleted unnecessary expanded widget
  lib/pages/courses/course_page.dart
Labels: bug

#25 feat(auth): BLoC with backend connection
  lib/components/bloc_text_field.dart
  lib/components/info_card.dart
  lib/components/profile_avatar.dart
  lib/layout/app_layout.dart
  lib/layout/app_theme.dart
  lib/main.dart
  lib/pages/auth/bloc/auth_bloc.dart
  lib/pages/auth/bloc/auth_event.dart
  lib/pages/auth/bloc/auth_state.dart
  lib/pages/auth/bloc/login_bloc.dart
  lib/pages/auth/bloc/login_event.dart
  lib/pages/auth/bloc/login_state.dart
  lib/pages/auth/bloc/sign_up_bloc.dart
  lib/pages/auth/bloc/sign_up_event.dart
  lib/pages/auth/bloc/sign_up_state.dart
  lib/pages/auth/components/auth_button.dart
  lib/pages/auth/model/email_field.dart
  lib/pages/auth/model/full_name_field.dart
  lib/pages/auth/model/password_confirmation_field.dart
  lib/pages/auth/model/password_field.dart
  lib/pages/auth/model/phone_field.dart
  lib/pages/auth/repository/auth_repository.dart
  lib/pages/auth/sign_in_page.dart
  lib/pages/auth/sign_up_page.dart
  lib/pages/home/home_today_page.dart
  lib/pages/profile/profile_settings_page.dart
  lib/utils/formz_state.dart
  pubspec.lock
  pubspec.yaml
  test/routing_test.dart
Labels: enhancement

#26 feat(courses): routing
  lib/layout/route_constants.dart
  lib/pages/courses/course_page.dart
  lib/pages/courses/courses_location.dart
  lib/pages/courses/courses_page.dart
  lib/pages/home/home_courses_page.dart
  lib/pages/home/home_today_page.dart
Labels: enhancement

#27 fix(android): missing internet access permission
  android/app/src/main/AndroidManifest.xml
Labels: bug

#28 test(routing): fixed tests to include auth
  lib/pages/auth/repository/auth_repository.dart
  lib/pages/auth/sign_in_page.dart
  test/routing_test.dart
Labels: test

#30 feat: Daily advice
  lib/components/daily_advice.dart
  lib/pages/home/home_today_page.dart
  lib/utils/fetch_advice.dart
Labels: enhancement

#31 feat: Terms and Conditions
  lib/pages/auth/sign_up_page.dart
Labels: enhancement
